version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8181:80
    php:
        build: containers/php_custom # Get our Dockerfile configuration
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ./openskedge:/var/www/openskedge
    web:
        image: nginx
        links:
            - php
        volumes_from:
            - php
        volumes:
        - ./containers/nginx/site.template:/etc/nginx/conf.d/mysite.template
        - ./containers/logs/nginx/:/var/log/nginx
        ports:
        - "8080:80"
        environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
