version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        links:
            - db
        ports:
            - 8181:80
    php:
        build: containers/php_custom # Get our Dockerfile configuration
        depends_on:
            - db
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ./OpenSkedge-lelefan:/var/www/serving_website
    web:
        image: nginx
        depends_on:
            - php
        links:
            - php
        volumes_from:
            - php
        volumes:
        - ./containers/nginx/site.template:/etc/nginx/conf.d/default.conf
        - ./containers/logs/nginx/:/var/log/nginx
        ports:
            - "8008:80"
        # environment:
        #     - NGINX_HOST=localhost
        #     - NGINX_PORT=80
        # command: /bin/bash -c "echo 'Updating configuration with environment' && envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && echo 'Starting NGINX' && nginx -g 'daemon off;'"
