parameters:
    # Database Configuration
    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: your_database_name
    database_user: your_user_name
    database_password: your_user_pass
    database_path: null

    # Mailer Configuration
    sender_email: no-reply@yourdomain.com
    mailer_transport: smtp
    mailer_encryption: tls
    mailer_auth: login
    mailer_port: 587
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

    # Locale Configuration
    locale: en

    # Security Configuration
    secret: YOU_NEED_SOME_GOBBLEDIEGOOK_HERE
    protocol: http   # http or https (recommended)

    # Session Configuration
    session_handler: ~
    # If you want to use memcache for session storage
    #  session_handler: session.handler.memcache
    session_memcache_host: 127.0.0.1
    session_memcache_port: 11211
    session_memcache_prefix: openskedge
    session_memcache_expire: 3600
